[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  let g:unite_source_history_yank_enable = 1
'''
depends = 'neomru.vim'

#-- PYTHON ----------------------------------------------------------
# jedi-vim
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
  let g:jedi#rename_command = "<leader>R"
'''
hook_source = 'source ~/.vim/rc/plugins/jedi-vim.rc.vim'

# vim-commentary
[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
  autocmd FileType python setlocal commentstring=#\ %s
'''
on_ft = 'python'

#--------------------------------------------------------------------
# textobj
[[plugins]]
repo = 'bps/vim-textobj-python'
depends = 'vim-textobj-user'
on_ft = 'python'

#--------------------------------------------------------------------
# vim-quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
hook_add = '''
  " Run quickrun after saving files by \r
  let g:quickrun_no_default_key_mappings = 1
  nnoremap \r :write<CR>:QuickRun -mode n<CR>
  xnoremap \r :<C-U>write<CR>gv:QuickRun -mode v<CR>
'''
hook_source = 'source ~/.vim/rc/plugins/vim_quickrun.rc.vim'

#--------------------------------------------------------------------

